---
resources: 
- name: image-rhel7
  type: git
  source:
    uri: https://github.com/mariuszdotnet/image-rhel7
    branch: master

- name: image-artifact
  type: git
  source:
    uri: https://github.com/mariuszdotnet/image-artifact
    branch: image-master-rhel7-na
    private_key: ((github-private-key))

- name: image-configuration
  type: git
  source:
    uri: https://github.com/mariuszdotnet/image-configuration
    branch: master

- name: image-secret
  type: git
  source:
    uri: https://supermarioworld.visualstudio.com/image-pipeline/image-pipeline%20Team/_git/image-secret
    branch: master
    username: ((vsts-user))
    password: ((vsts-secret))

- name: image-concourse-pipeline
  type: git
  source:
    uri: https://github.com/mariuszdotnet/image-concourse-pipeline
    branch: master

jobs:
- name: na-image-build-job
  public: true
  plan:
  - aggregate:
    - get: image-concourse-pipeline
    - get: image-rhel7
    - get: image-artifact
    - get: image-configuration
    - get: image-secret
  - task: build-image-task
    file: image-concourse-pipeline/tasks/build-image-task.yml
