---
resources: 
- name: image-rhel7
  type: git
  source:
    uri: https://github.com/mariuszdotnet/image-rhel7
    branch: master

- name: image-concourse-pipeline
  type: git
  source:
    uri: https://github.com/mariuszdotnet/image-concourse-pipeline
    branch: master

jobs:
- name: na-image-build-job
  public: true
  plan:
  - aggregate:
    - get: image-concourse-pipeline
    - get: image-rhel7
  - task: build-image-task
    file: image-concourse-pipeline/tasks/build-image-task.yml
