---
resources: 
- name: image-concourse-pipeline
  type: git
  source:
    uri: https://github.com/mariuszdotnet/image-concourse-pipeline
    branch: master

jobs:
- name: na-image-build-job
  public: true
  plan:
  - aggregate:
    - get: image-concourse-pipeline
  - task: build-image-task
    file: image-concourse-pipeline/build-image-task.yml
