---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: hashicorp/packer
    tag: light

inputs:
  - name: image-concourse-pipeline

run:
  #path: ./image-concourse-pipeline/tasks/build-image-task.sh
  path: packer
  args: [-v]