---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: hashicorp/packer
    tag: light

inputs:
  - name: image-rhel7
  - name: image-artifact
  - name: image-configuration
  - name: image-secret
  - name: image-concourse-pipeline

run:
  path: ./image-concourse-pipeline/tasks/build-image-task.sh
  #path: ls
  #args: [-al]