---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: hashicorp/packer
    tag: light

inputs:
  - name: image-rhel7

run:
  #path: ./packer-build-tasks/packer-win-vhd-build.sh
  path: ls
  args: [-al]